### ISSUE TITLE
新版本修改后不能使用，作者麻烦更新下

### ISSUE THREAD

**Issue by vay1314** [ZHDeveloper/TweakPingAnRun#3]
之前使用的旧版平安金管家修改后一直正常使用，昨天平安检测旧版本不让登陆了，使用新版本修改后不能打开了，请作者麻烦更新下

**Comment by ZHDeveloper** [comment]
已更新，适配平安金管家5.0

**Comment by vay1314** [comment]
> 已更新，适配平安金管家5.0

十分感谢
